--A)
DECLARE
    V_APE EMPLE.APELLIDO%TYPE;
    V_SAL EMPLE.SALARIO%TYPE;
BEGIN
    SELECT APELLIDO, SALARIO INTO V_APE, V_SAL
    FROM EMPLE
    WHERE EMP_NO = 7698;
    DBMS_OUTPUT.PUT_LINE(V_APE || ' ' || V_SAL);
END;
/

--B)
DECLARE
    V_APE EMPLE.APELLIDO%TYPE;
    V_SAL EMPLE.SALARIO%TYPE;
    V_DNO DEPART.DNOMBRE%TYPE;
BEGIN
    SELECT APELLIDO, SALARIO, DNOMBRE INTO V_APE, V_SAL, V_DNO
    FROM EMPLE
    INNER JOIN DEPART ON EMPLE.DEPT_NO = DEPART.DEPT_NO
    WHERE EMP_NO = 7698;
    DBMS_OUTPUT.PUT_LINE(V_APE || ' ' || V_SAL || ' ' || V_DNO);
END;
/

--C)
DECLARE
    V_APE EMPLE.APELLIDO%TYPE;
    V_SAL EMPLE.SALARIO%TYPE;
    V_DNO DEPART.DNOMBRE%TYPE;
BEGIN
    SELECT APELLIDO, SALARIO, DNOMBRE INTO V_APE, V_SAL, V_DNO
    FROM EMPLE
    INNER JOIN DEPART ON EMPLE.DEPT_NO = DEPART.DEPT_NO
    WHERE EMP_NO = &EMP_NO;
    DBMS_OUTPUT.PUT_LINE(V_APE || ' ' || V_SAL || ' ' || V_DNO);
END;
/

--D)
DECLARE
    V_OFI EMPLE.OFICIO%TYPE;
    V_SAL EMPLE.SALARIO%TYPE;
BEGIN
    SELECT DISTINCT OFICIO, SALARIO INTO V_OFI, V_SAL
    FROM EMPLE
    WHERE SALARIO = (SELECT MAX(SALARIO)
                     FROM EMPLE);
    DBMS_OUTPUT.PUT_LINE('El oficio mejor pagado es ' || 
        V_OFI || ' con un salario de ' || V_SAL);
END;
/

--E)
DECLARE
    V_EMP EMPLE%ROWTYPE;
BEGIN
    SELECT * INTO V_EMP
    FROM EMPLE
    WHERE EMP_NO = 7876;
    
    DBMS_OUTPUT.PUT_LINE('Los datos del empleado 7876 son:' || '
        - APELLIDO: ' || V_EMP.APELLIDO || ' 
        - OFICIO: ' || V_EMP.OFICIO || ' 
        - DIRECTOR: ' || V_EMP.DIR || ' 
        - FECHA ALTA: ' || V_EMP.FECHA_ALT || ' 
        - SALARIO: ' || V_EMP.SALARIO || '
        - COMISIÓN: ' || V_EMP.COMISION || '
        - NÚMERO DE DEPARTAMENTO: ' || V_EMP.DEPT_NO);
END;
/