CREATE TABLE AUDITAR_EMPLE (
    REGISTRO VARCHAR2(200) PRIMARY KEY
);

CREATE OR REPLACE
TRIGGER AUDITAR_CAMBIO_SALARIO
AFTER UPDATE OF SALARIO ON EMPLE
FOR EACH ROW

DECLARE
    V_PORCENTAJE NUMBER(3);
    V_SUB_BAJ CHAR(6);
BEGIN
    V_PORCENTAJE := ((:NEW.SALARIO - :OLD.SALARIO) / :OLD.SALARIO) * 100;
    
    IF V_PORCENTAJE > 0 THEN
        V_SUB_BAJ := 'subida';
    ELSE
        V_SUB_BAJ := 'bajada';
    END IF;
    
    INSERT INTO AUDITAR_EMPLE(REGISTRO)
    VALUES(TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS') || ' Empleado ' 
           || :OLD.EMP_NO || ': ' || V_SUB_BAJ || ' de salario ' 
           || V_PORCENTAJE || '% (' || :OLD.SALARIO || ' -> ' || :NEW.SALARIO 
           || ')');
END;
/

UPDATE EMPLE
    SET SALARIO = 2500
    WHERE EMP_NO = 7839;

UPDATE EMPLE
    SET SALARIO = 2250
    WHERE EMP_NO = 7839;

SELECT *
FROM AUDITAR_EMPLE;