--CREAR TABLA
CREATE TABLE ejemplo_check
(
    nif VARCHAR2(9) PRIMARY KEY,
    nombre VARCHAR2(30) NOT NULL,
    edad NUMBER(3) CHECK (edad BETWEEN 12 AND 18),
    curso NUMBER(1),
        CHECK (curso IN (1, 2, 3))
);

--INSERTAR CAMPOS QUE ACEPTEN Y VIOLEN LAS RESTRICCIONES
/* INSERCIÓN VÁLIDA */
INSERT INTO ejemplo_check VALUES ('10000000A', 'Luis', 12, 1);

/* INSERCCIÓN QUE VIOLA EL CHECK DE EDAD */
INSERT INTO ejemplo_check VALUES ('20000000A', 'Esteban', 19, 1);

/* INSERCCIÓN QUE VIOLA EL CHECK DE CURSO*/
INSERT INTO ejemplo_check VALUES ('30000000A', 'Lucia', 13, 4);

/* INSERCCIÓN QUE VIOLA LA PRIMARY KEY */
INSERT INTO ejemplo_check VALUES ('10000000A', 'Luisa', 19, 4);

/* INSERCCIÓN QUE VIOLA EL NOT NULL DE NOMBRE */
INSERT INTO ejemplo_check VALUES ('20000000A', NULL, 19, 4);

--INSERTAR VALORES NULL
INSERT INTO ejemplo_check VALUES ('20000000A', 'Paco', NULL, NULL);

--VISUALIZAR REGISTROS
SELECT * FROM ejemplo_check;
