--INSERTAR EN TABLA DE MIGUELANGEL
INSERT INTO MIGUELANGEL.TEMPER_HIST VALUES('Madrid','05/02/2021',15);
--INTENTAR REGISTRO TRAS REVOKE
INSERT INTO MIGUELANGEL.TEMPER_HIST VALUES('Madrid','10/02/2021',14);
--COMPROBAR PERMISOS
SELECT * FROM SESSION_PRIVS;