SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'EJEMPLO_CONST_NOTNULL';
SELECT * FROM USER_CONS_COLUMNS WHERE TABLE_NAME = 'EJEMPLO_CONST_NOTNULL';

SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'AUTOR';
SELECT * FROM USER_CONS_COLUMNS WHERE TABLE_NAME = 'AUTOR';

SELECT * FROM USER_CONSTRAINTS;
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'SYS_C009651';