--CREAR TABLA
CREATE TABLE EJEMPLO_ALTER
(
    campo1 NUMBER(2) PRIMARY KEY
);

--INSERTAR REGISTROS
INSERT INTO EJEMPLO_ALTER VALUES(1);
INSERT INTO EJEMPLO_ALTER VALUES(2);

--AÑADIR COLUMNA
ALTER TABLE EJEMPLO_ALTER ADD campo2 NUMBER(3);

--DESCRIBE Y SELECT
DESCRIBE EJEMPLO_ALTER;
SELECT * FROM EJEMPLO_ALTER;

--AÑADIR UNA COLUMNA CON RESTRICCIÓN
ALTER TABLE EJEMPLO_ALTER ADD campo3 VARCHAR2(10) CHECK(campo3 NOT LIKE 'E%');

--DESCRIBE Y RESTRICCIONES
DESCRIBE EJEMPLO_ALTER;
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME='EJEMPLO_ALTER';

--INSERTAR UNA RESTRICCIÓN NOT NULL SIN TRUNCAR TABLA
ALTER TABLE EJEMPLO_ALTER ADD campo4 CHAR(1) NOT NULL;

--INSERTAR UNA RESTRICCIÓN NOT NULL TRUNCANDO TABLA
TRUNCATE TABLE EJEMPLO_ALTER;
ALTER TABLE EJEMPLO_ALTER ADD campo4 CHAR(1) NOT NULL;

--AÑADIR UNA RESTRICCIÓN A LA TABLA
ALTER TABLE EJEMPLO_ALTER ADD CONSTRAINT CAMPO3_NOREPETIDO UNIQUE(campo3);

--DESCRIBE
DESCRIBE EJEMPLO_ALTER;

--RESTRICCIONES DE LA TABLA
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME='EJEMPLO_ALTER';

--MODIFICACIÓN DEL TIPO DE DATOS
ALTER TABLE EJEMPLO_ALTER MODIFY campo2 DATE;

--AÑADIR UNA RESTRICCIÓN DE COLUMNA
ALTER TABLE EJEMPLO_ALTER MODIFY campo4 CHECK(campo4 IN('X','Y','Z'));

--COMPROBAR EL FUNCIONAMIENTO DE LA RESTRICCION
INSERT INTO EJEMPLO_ALTER VALUES (15,'10/10/2020','AAA','F');

--COMPROBAR FUNCIONAMIENTO DE COMANDO
ALTER TABLE EJEMPLO_ALTER MODIFY campo1 NUMBER(2);
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME='EJEMPLO_ALTER';

--BORRAR COLUMNA
ALTER TABLE EJEMPLO_ALTER DROP COLUMN campo4;

--BORRAR RESTRICCIONES DE LA TABLA
ALTER TABLE EJEMPLO_ALTER DROP CONSTRAINT CAMPO3_NOREPETIDO;

--BORRAR CLAVE PRIMARIA
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME='EJEMPLO_ALTER';
ALTER TABLE EJEMPLO_ALTER DROP CONSTRAINT SYS_C0011282;

--DESHABILITAR RESTRICCIONES
ALTER TABLE EJEMPLO_ALTER MODIFY campo1 PRIMARY KEY;
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME='EJEMPLO_ALTER';
ALTER TABLE EJEMPLO_ALTER DISABLE CONSTRAINT SYS_C0011287;
