--VER LOS DISTINTOS TIPOS DE OBJETOS QUE TIENE CREADO NUESTRO USUARIO;
SELECT DISTINCT OBJECT_TYPE FROM USER_OBJECTS; 
--VER LAS TABLAS CREADAS POR EL USUARIO
SELECT * FROM USER_TABLES;
--VER NÚMERO DE TABLAS CREADAS POR EL USUARIO
SELECT COUNT(*) FROM USER_TABLES;
--VER TODAS LAS TABLAS (A LAS QUE SE TIENE PERMISO)
SELECT * FROM ALL_TABLES; 
--VER NÚMERO DE TABLAS
SELECT COUNT(*) FROM ALL_TABLES;
--VER ESTRUCTURA DE LA VISTA
DESCRIBE USER_TABLES;