--CREACION DE LAS TABLAS
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY';
CREATE TABLE TEMPER_ACT
(
    ciudad VARCHAR2(50) PRIMARY KEY,
    temperatura NUMBER(2) CHECK (temperatura BETWEEN -20 AND 50)
);

INSERT INTO TEMPER_ACT VALUES('Segovia',11);
INSERT INTO TEMPER_ACT VALUES('Guadalajara',7);
INSERT INTO TEMPER_ACT VALUES('Granada',13);
INSERT INTO TEMPER_ACT VALUES('Lugo',15);
INSERT INTO TEMPER_ACT VALUES('Ibiza',14);

CREATE TABLE TEMPER_HIST
(
    ciudad VARCHAR2(50),
    fecha DATE,
    temperatura NUMBER(2) CHECK (temperatura BETWEEN -20 AND 50),
        PRIMARY KEY(ciudad,fecha)
);

INSERT INTO TEMPER_HIST VALUES('Segovia','05/02/2021',10);
INSERT INTO TEMPER_HIST VALUES('Segovia','04/02/2021',10);
INSERT INTO TEMPER_HIST VALUES('Segovia','29/01/2021',5);
INSERT INTO TEMPER_HIST VALUES('Guadalajara','05/02/2021',4);
INSERT INTO TEMPER_HIST VALUES('Guadalajara','25/01/2021',-1);
INSERT INTO TEMPER_HIST VALUES('Granada','04/02/2021',13);
INSERT INTO TEMPER_HIST VALUES('Lugo','03/02/2021',15);
INSERT INTO TEMPER_HIST VALUES('Lugo','01/02/2021',13);
INSERT INTO TEMPER_HIST VALUES('Ibiza','05/02/2021',14);
INSERT INTO TEMPER_HIST VALUES('Ibiza','04/02/2021',12);

COMMIT;

--PERMISOS A ALUMNO
GRANT SELECT ON TEMPER_ACT TO ALUMNO;
GRANT INSERT ON TEMPER_HIST TO ALUMNO;
GRANT ALL ON TEMPER_HIST TO ALUMNO;