ALTER SESSION SET CONTAINER = XEPDB1;

--COMANDO PARA ACTIVAR LOS PERFILES
ALTER SYSTEM SET RESOURCE_LIMIT=TRUE;

--CREACIÓN DEL PERFIL
CREATE PROFILE REPONEDOR LIMIT
    SESSIONS_PER_USER 1
    CONNECT_TIME 2;

--ASIGNAR PERFIL
ALTER USER MIGUELANGEL PROFILE REPONEDOR;