--COMPROBAR PARÁMETROS DEL USUARIO
SELECT * FROM USER_USERS;

--CAMBIAR CONTRASEÑA
ALTER USER MIGUELANGEL IDENTIFIED BY miguela;

--INTENTAR CREAR TABLA
CREATE TABLE PRUEBA
(
    cod NUMBER(3) PRIMARY KEY
);