DROP TABLE PROFESOR cascade constraints; 

CREATE TABLE PROFESOR (
 COD_CENTRO   NUMBER(4) default 0,
 DNI          VARCHAR2(9) primary key,
 ESPECIALIDAD VARCHAR2(20),
 NOMBRECOMPLETO VARCHAR2(30)
) ;

INSERT INTO PROFESOR (DNI, ESPECIALIDAD, NOMBRECOMPLETO)
VALUES ('11111111A', 'Ciencias Sociales', 'Elisa Sánchez');

INSERT INTO PROFESOR 
VALUES (NULL, '22222222A', 'Literatura', 'Erika Jiménez');

SELECT *
FROM PROFESOR;