--A
DROP TABLE ALUM cascade constraints;
DROP TABLE NUEVOS cascade constraints;
DROP TABLE ANTIGUOS cascade constraints;

Create TABLE ALUM
(
NOMBRE VARCHAR2(20),
EDAD NUMBER(2),
LOCALIDAD VARCHAR2(15),
PRIMARY KEY(NOMBRE,EDAD,LOCALIDAD)
) ;

Create TABLE  NUEVOS
(
NOMBRE  VARCHAR2(20),
EDAD NUMBER(2),
LOCALIDAD VARCHAR2(15),
PRIMARY KEY(NOMBRE,EDAD,LOCALIDAD)
) ;

Create TABLE ANTIGUOS
(
NOMBRE  VARCHAR2(20),
EDAD NUMBER(2),
LOCALIDAD VARCHAR2(15),
PRIMARY KEY(NOMBRE,EDAD,LOCALIDAD)
) ;

INSERT INTO ALUM VALUES('JUAN',18,'COSLADA');
INSERT INTO ALUM VALUES('PEDRO',19,'COSLADA');
INSERT INTO ALUM VALUES('ANA',17,'ALCALÁ');
INSERT INTO ALUM VALUES('LUISA',18,'TORREJÓN');
INSERT INTO ALUM VALUES('MARÍA',20,'MADRID');
INSERT INTO ALUM VALUES('ERNESTO',21,'MADRID');
INSERT INTO ALUM VALUES('RAQUEL',19,'TOLEDO');

INSERT INTO NUEVOS VALUES('JUAN',18,'COSLADA');
INSERT INTO NUEVOS VALUES('MAITE',15,'ALCALÁ');
INSERT INTO NUEVOS VALUES('SOFÍA',14,'ALCALÁ');
INSERT INTO NUEVOS VALUES('ANA',17,'ALCALÁ');
INSERT INTO NUEVOS VALUES('ERNESTO',21,'MADRID');

INSERT INTO ANTIGUOS VALUES('MARÍA',23,'MADRID');
INSERT INTO ANTIGUOS VALUES('ERNESTO',21,'MADRID');
INSERT INTO ANTIGUOS VALUES('ANDRÉS',26,'LAS ROZAS');
INSERT INTO ANTIGUOS VALUES('IRENE',24,'LAS ROZAS');

COMMIT;

SELECT *
FROM ALUM;

SELECT *
FROM NUEVOS;

--INSERCIÓN DE DATOS
INSERT INTO ALUM
    SELECT *
    FROM NUEVOS
    WHERE (NOMBRE, EDAD, LOCALIDAD) NOT IN (SELECT *
                                            FROM ALUM);

/*Otra forma de hacerlo*/
INSERT INTO ALUM
    SELECT * FROM ALUM
    MINUS
    SELECT * FROM NUEVOS;

--BORRADO DE DATOS
DELETE 
FROM NUEVOS;

/*Otra forma de hacerlo*/
TRUNCATE TABLE NUEVOS;

--B
SELECT *
FROM EMPLE;

INSERT INTO EMPLE
    SELECT 2000, 'SAAVEDRA', OFICIO, DIR, (SYSDATE - 1), (SALARIO * 1.2),
        COMISION, DEPT_NO
    FROM EMPLE
    WHERE APELLIDO = 'SALA';