--A

CREATE TABLE DESARROLLADORES (NUMERO_EMPLE, EMPLEADO, DEPARTAMENTO)
AS
SELECT EMP_NO, APELLIDO, DNOMBRE
FROM EMPLE E
INNER JOIN DEPART D ON E.DEPT_NO = D.DEPT_NO
WHERE OFICIO = 'DESARROLLADOR';

--B
DESCRIBE DESARROLLADORES;

SELECT *
FROM DESARROLLADORES;

--C
SELECT *
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'DESARROLLADORES';

SELECT *
FROM USER_CONS_COLUMNS
WHERE TABLE_NAME = 'DESARROLLADORES';

--D
ALTER TABLE DESARROLLADORES
ADD CONSTRAINT PK_DESARROLLADORES PRIMARY KEY (NUMERO_EMPLE);

ALTER TABLE DESARROLLADORES
ADD CONSTRAINT FK_DESARROLLADORES_EMPLE FOREIGN KEY (NUMERO_EMPLE)
    REFERENCES EMPLE (EMP_NO) ON DELETE CASCADE;