--A)
CREATE OR REPLACE TYPE PRECIO_FUNCION AS OBJECT(
    INFANTIL    NUMBER(5,2),
    GENERAL     NUMBER(5,2),
    REDUCIDA    NUMBER(5,2)
);
/

--B)
CREATE TABLE FUNCIONES(
    OBRA    VARCHAR2(35),
    HORA    VARCHAR2(5),
    PRECIO  PRECIO_FUNCION,
        CONSTRAINT PK_FUNCIONES PRIMARY KEY(OBRA, HORA),
        CONSTRAINT CK_HORA_FORMATO CHECK(HORA LIKE '__:__')
);

--C)
INSERT INTO FUNCIONES
    VALUES('EL VERDUGO', '19:00', PRECIO_FUNCION(14.50, 22, 18));

INSERT INTO FUNCIONES
    VALUES('EL VERDUGO', '21:00', PRECIO_FUNCION(15.50, 24, 20));
    
--D)
UPDATE FUNCIONES F
    SET F.PRECIO.REDUCIDA = 18
    WHERE OBRA = 'EL VERDUGO'
        AND HORA = '21:00';

SELECT F.PRECIO.REDUCIDA
FROM FUNCIONES F
WHERE OBRA = 'EL VERDUGO'
    AND HORA = '21:00';