--A)
CREATE OR REPLACE TYPE TARJETAS AS OBJECT(
    CLASE   VARCHAR2(20),
    NUMERO  NUMBER(16)
);
/

--B)
CREATE OR REPLACE TYPE CARTERA
AS TABLE OF TARJETAS;
/

--C)
CREATE TABLE CLIENTES_TIENDA(
    ID_CLIENTE  NUMBER(2)   PRIMARY KEY,
    NOMBRE      VARCHAR2(50),
    APELLIDO    VARCHAR2(50),
    DIRECCION   VARCHAR2(50),
    TARJETAS    CARTERA
) NESTED TABLE TARJETAS STORE AS T_TARJETAS;

--D)
INSERT INTO CLIENTES_TIENDA
    VALUES(1, 'PACO', 'ROMERO', 'REAL 10',
        CARTERA(TARJETAS('VISA DÉBITO', 0000000000),
                TARJETAS('MASTERCARD', 0000000001)));

INSERT INTO CLIENTES_TIENDA
    VALUES(2, 'MARÍA', 'JIMÉNEZ', 'GRAN VÍA 1',
        CARTERA(TARJETAS('VISA ORO', 0000000002),
                TARJETAS('AMERICAN E', 0000000003),
                TARJETAS('VISA CRÉDITO', 0000000004)));

--E)
SELECT *
FROM CLIENTES_TIENDA;

--BLOQUE ANÓNIMO PARA LA SALIDA COMPLETA DE DATOS
DECLARE
  V_CLI CLIENTES_TIENDA%ROWTYPE; --VARIABLE DONDE GUARDAR CADA FILA DE LA TABLA.
  V_CON NUMBER(2);               --VARIABLE QUE HARÁ LA FUNCIÓN DE CONTADOR.
BEGIN
  FOR V_CLI IN (SELECT * FROM CLIENTES_TIENDA) LOOP
    V_CON := 1;
    DBMS_OUTPUT.PUT_LINE('ID_CLIENTE: ' || V_CLI.ID_CLIENTE);
    DBMS_OUTPUT.PUT_LINE('  - NOMBRE: ' || V_CLI.NOMBRE);
    DBMS_OUTPUT.PUT_LINE('  - APELLIDO: ' || V_CLI.APELLIDO);
    DBMS_OUTPUT.PUT_LINE('  - DIRECCION: ' || V_CLI.DIRECCION);
    FOR i IN V_CLI.TARJETAS.FIRST .. V_CLI.TARJETAS.LAST LOOP
        DBMS_OUTPUT.PUT_LINE('  - TARJETA ' || V_CON);
        DBMS_OUTPUT.PUT_LINE('    - CLASE: ' || V_CLI.TARJETAS(i).CLASE);
        DBMS_OUTPUT.PUT_LINE('    - NUMERO: ' || V_CLI.TARJETAS(i).NUMERO);
        V_CON := V_CON + 1;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('----------------------------------------------------');
  END LOOP;
END;
/