--A)
CREATE OR REPLACE TYPE TABLA_HIJOS
AS TABLE OF VARCHAR(50);
/

--B)
CREATE TABLE EMPLE_HIJOS2(
    ID_PERSONA  NUMBER(1)       PRIMARY KEY,
    NOMBRE      VARCHAR2(50)    NOT NULL,
    APELLIDO1   VARCHAR2(50)    NOT NULL,
    APELLIDO2   VARCHAR2(50)    NOT NULL,
    HIJOS       TABLA_HIJOS
) NESTED TABLE HIJOS STORE AS T_HIJOS;

--C)
INSERT INTO EMPLE_HIJOS2 (ID_PERSONA, NOMBRE, APELLIDO1, APELLIDO2, HIJOS)
    VALUES (1, 'FRANCISCO', 'ROMERO', 'TORRES', TABLA_HIJOS('LUISA', 'ALBA'));

INSERT INTO EMPLE_HIJOS2 (ID_PERSONA, NOMBRE, APELLIDO1, APELLIDO2, HIJOS)
    VALUES (2, 'JULIETA', 'JIMÉNEZ', 'LÓPEZ', 
        TABLA_HIJOS('CARLOS', 'JOSÉ', 'PEDRO'));

--D)
SELECT *
FROM EMPLE_HIJOS2;

--D)
DECLARE
   V_EMPLEADO   EMPLE_HIJOS2%ROWTYPE;
BEGIN
    SELECT *
        INTO V_EMPLEADO
    FROM EMPLE_HIJOS2
    WHERE ID_PERSONA = &ID_PERSONA;
    DBMS_OUTPUT.PUT_LINE('Hijos del empleado '||V_EMPLEADO.NOMBRE||' '
        ||V_EMPLEADO.APELLIDO1||' '||V_EMPLEADO.APELLIDO2||':');
    FOR i in V_EMPLEADO.HIJOS.FIRST .. V_EMPLEADO.HIJOS.LAST LOOP
          DBMS_OUTPUT.PUT_LINE(V_EMPLEADO.HIJOS(i));
    END LOOP;
END;
/