--A)
CREATE OR REPLACE TYPE CUENTA AS OBJECT(
    NUMERO_CUENTA   NUMBER(6),
    TITULAR         VARCHAR2(30),
    SALDO           NUMBER(30)
);
/

--B)
CREATE TABLE SUCURSAL OF CUENTA;

--C)
INSERT INTO SUCURSAL (NUMERO_CUENTA, TITULAR, SALDO)
    VALUES (000001, 'PACO ROMERO', 1000000);

INSERT INTO SUCURSAL (NUMERO_CUENTA, TITULAR, SALDO)
    VALUES (000002, 'MARÍA JIMÉNEZ', 25000);

--D)
SELECT *
FROM SUCURSAL;

--E)
DELETE
    FROM SUCURSAL
    WHERE NUMERO_CUENTA = 000002;