--A)
CREATE OR REPLACE TYPE COLEC_HIJOS
AS VARRAY(10) OF VARCHAR2(50);
/

--B)
CREATE TABLE EMPLE_HIJOS1(
    ID_PERSONA  NUMBER(1)       PRIMARY KEY,
    NOMBRE      VARCHAR2(50)    NOT NULL,
    APELLIDO1   VARCHAR2(50)    NOT NULL,
    APELLIDO2   VARCHAR2(50)    NOT NULL,
    HIJOS       COLEC_HIJOS
);

--C)
INSERT INTO EMPLE_HIJOS1 (ID_PERSONA, NOMBRE, APELLIDO1, APELLIDO2, HIJOS)
    VALUES (1, 'FRANCISCO', 'ROMERO', 'TORRES', COLEC_HIJOS('LUISA', 'ALBA'));

INSERT INTO EMPLE_HIJOS1 (ID_PERSONA, NOMBRE, APELLIDO1, APELLIDO2, HIJOS)
    VALUES (2, 'JULIETA', 'JIMÉNEZ', 'LÓPEZ', 
        COLEC_HIJOS('CARLOS', 'JOSÉ', 'PEDRO'));

--D)
SELECT *
FROM EMPLE_HIJOS1;

--D)
DECLARE
   V_EMPLEADO   EMPLE_HIJOS1%ROWTYPE;
BEGIN
    SELECT *
        INTO V_EMPLEADO
    FROM EMPLE_HIJOS1
    WHERE ID_PERSONA = &ID_PERSONA;
    DBMS_OUTPUT.PUT_LINE('Hijos del empleado '||V_EMPLEADO.NOMBRE||' '
        ||V_EMPLEADO.APELLIDO1||' '||V_EMPLEADO.APELLIDO2||':');
    FOR i in V_EMPLEADO.HIJOS.FIRST .. V_EMPLEADO.HIJOS.LAST LOOP
          DBMS_OUTPUT.PUT_LINE(V_EMPLEADO.HIJOS(i));
    END LOOP;
END;
/