--A)
CREATE OR REPLACE TYPE TIPO_CIUDADANO AS OBJECT(
    NIF         CHAR(9),
    NOMBRE      VARCHAR2(30),
    APELLIDOS   VARCHAR2(60),
    EMAIL       VARCHAR2(120),
    MEMBER FUNCTION NOMBRECOMPLETO RETURN VARCHAR2
);
/

--B)
CREATE OR REPLACE TYPE BODY TIPO_CIUDADANO AS
MEMBER FUNCTION NOMBRECOMPLETO RETURN VARCHAR2
    AS
    BEGIN
        RETURN (NOMBRE||' '||APELLIDOS);
    END;
END;
/

--C)
CREATE TABLE CIUDADANOS(
    IDCIUDADANO NUMBER(2)       PRIMARY KEY,
    CIUDADANO   TIPO_CIUDADANO  NOT NULL,
    CIUDAD      VARCHAR2(60)
);

--D)
INSERT INTO CIUDADANOS
    VALUES(1, TIPO_CIUDADANO('11111111N', 'Paco', 'Pérez Agudo', 'pp@mail.com'),
        'Coslada');

INSERT INTO CIUDADANOS
    VALUES(2, TIPO_CIUDADANO('22222222N', 'María', 'Mesa Martí', 'mm@mail.com'),
        'San Fernando de Henares');

--E)
SELECT IDCIUDADANO, C.CIUDADANO.NIF NIF, C.CIUDADANO.NOMBRECOMPLETO()
    NOMBRECOMPLETO, CIUDAD
FROM CIUDADANOS C;