--A)
CREATE OR REPLACE TYPE TIPO_PERSONA AS OBJECT(
    NIF         CHAR(9),
    NOMBRE      VARCHAR2(30),
    APELLIDOS   VARCHAR2(60),
    EMAIL       VARCHAR2(120)
) NOT FINAL;
/

--B)
CREATE OR REPLACE TYPE TIPO_TRABAJADOR 
UNDER TIPO_PERSONA(
    INSTITUTO   VARCHAR2(30),
    PUESTO      VARCHAR2(10)
) NOT FINAL;
/

--C)
CREATE OR REPLACE TYPE TIPO_PROFESOR
UNDER TIPO_TRABAJADOR(
    CUERPO      VARCHAR2(30),
    TITULACION  VARCHAR2(30)
);
/

--D)
CREATE TABLE CONSERJES OF TIPO_TRABAJADOR;
CREATE TABLE PROFESORES OF TIPO_PROFESOR;

DESCRIBE CONSERJES;
DESCRIBE PROFESORES;

--E)
INSERT INTO PROFESORES
    VALUES('00000000A', 'Mar', 'Borondo Jai', 'mm@iesluisbraille.es', 
        'IES Luis Braille', 'fijo', 'Informática', 'Ingeniería informática');

INSERT INTO CONSERJES
    VALUES('33333333A', 'Luis', 'Rivera Moya', 'rm@iesluisbraille.es',
        'IES Luis Braille', 'temporal');

SELECT *
FROM PROFESORES;

SELECT *
FROM CONSERJES;