--CREAR TABLA
CREATE TABLE EMPLEADOS
(
    codigo VARCHAR2(5) PRIMARY KEY,
    nombre VARCHAR2(50),
    apellidos VARCHAR2(50),
    sueldo NUMBER(4)
);

--CREAR UN INDICE
CREATE INDEX INDICE_NOMBRE ON EMPLEADOS(nombre);

--COMPROBAR INDICES
SELECT * FROM USER_INDEXES WHERE TABLE_NAME='EMPLEADOS';

--COMPROBAR CONSTRAINTS
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME='EMPLEADOS';