--CREAR TABLA
CREATE TABLE ESTABLECIMIENTOS
(
    nif VARCHAR2(10),
    nombre VARCHAR2(20),
    direccion VARCHAR2(20),
    codpostal NUMBER(5)
);

--AÑADIR RESTRICCIONES
ALTER TABLE ESTABLECIMIENTOS 
    ADD CONSTRAINT PK_ESTABLECIMIENTOS PRIMARY KEY(nif);
ALTER TABLE ESTABLECIMIENTOS 
    MODIFY direccion 
    CONSTRAINT C_DIRECCION_SIN_COMAS CHECK(direccion NOT LIKE '%,%');

--CAMBIAR LONGITUD "NOMBRE"
ALTER TABLE ESTABLECIMIENTOS MODIFY nombre VARCHAR2(30);

--DESACTIVAR RESTRICCION DE DIRECCION
ALTER TABLE ESTABLECIMIENTOS DISABLE CONSTRAINT C_DIRECCION_SIN_COMAS;