--CREAR TABLA
CREATE TABLE EJEMPLO_CONST_NOTNULL
(
    nif VARCHAR2(9) PRIMARY KEY,
    nombre VARCHAR2(15) NOT NULL,
    edad NUMBER(3) CONSTRAINT EDAD_OBLIGAT NOT NULL
);

--INSERCIONES
INSERT INTO EJEMPLO_CONST_NOTNULL(nif,edad) VALUES ('1111A', 20);
INSERT INTO EJEMPLO_CONST_NOTNULL(nif,nombre) VALUES ('2222B', 'Jose');