--CREAR UN ÍNDICE COMPUESTO
CREATE INDEX INDICE_NOMBRE_COMPLETO ON EMPLEADOS(nombre,apellidos);

--COMPROBAR INDICES
SELECT * FROM USER_INDEXES WHERE TABLE_NAME='EMPLEADOS';

--COMPROBAR CAMPOS ASOCIADOS A UN INDICE
SELECT * FROM USER_IND_COLUMNS WHERE TABLE_NAME='EMPLEADOS';