--SELECT DE TABLA DE MIGUELANGEL
SELECT * FROM MIGUELANGEL.TEMPER_ACT;
--INSERT EN TABLA DE MIGUELANGEL
INSERT INTO MIGUELANGEL.TEMPER_ACT VALUES ('Madrid',12);

--SELECT DE TABLA DE MIGUELANGEL (APARTADO D)
SELECT * FROM MIGUELANGEL.TEMPER_HIST;
--INSERT EN TABLA DE MIGUELANGEL (APARTADO D)
INSERT INTO MIGUELANGEL.TEMPER_HIST VALUES ('Madrid','04/02/2021',12);