--CAMBIO DE CONTENEDOR
ALTER SESSION SET CONTAINER = XEPDB1;

--CREACIÓN DE USUARIO
CREATE USER MIGUELANGEL IDENTIFIED BY 12345 QUOTA UNLIMITED ON USERS;

--CONCEDER PERMISOS DE CONEXIÓN
GRANT CREATE SESSION TO MIGUELANGEL;