--CREAR ROL
ALTER SESSION SET CONTAINER = XEPDB1;
CREATE ROLE JEFE;
GRANT CREATE ANY INDEX TO JEFE;

--CREAR ROL SUPERVISION
CREATE ROLE SUPERVISION;
GRANT SELECT ANY TABLE TO SUPERVISION;
GRANT UPDATE ON MIGUELANGEL.TEMPER_ACT TO SUPERVISION;

--COMPROBAR PRIVILEGIOS
SELECT * FROM ROLE_SYS_PRIVS WHERE ROLE = 'JEFE' OR ROLE = 'SUPERVISION';
SELECT * FROM ROLE_TAB_PRIVS WHERE ROLE = 'JEFE' OR ROLE = 'SUPERVISION';

--ASIGNAR ROLES A ALUMNO
GRANT JEFE TO ALUMNO;
GRANT SUPERVISION TO ALUMNO;

--ASIGNAR ROL POR DEFECTO
ALTER USER ALUMNO DEFAULT ROLE SUPERVISION;