ALTER SESSION SET CONTAINER = XEPDB1;

--MODIFICAR PERFIL REPONEDOR
ALTER PROFILE REPONEDOR LIMIT
    FAILED_LOGIN_ATTEMPTS 3;

--DESBLOQUEAR CUENTA
ALTER USER MIGUELANGEL ACCOUNT UNLOCK;

--MODIFICAR DEFAULT
ALTER PROFILE DEFAULT LIMIT
    PASSWORD_LIFE_TIME UNLIMITED;