--CREAR TABLA
CREATE TABLE EJEMPLO_DEFAULT
(
    nif VARCHAR2(9) PRIMARY KEY,
    nombre VARCHAR2(15) NOT NULL,
    edad NUMBER(3) DEFAULT 18,
    fecha_alta DATE DEFAULT SYSDATE
);

--INSERTAR REGISTROS
INSERT INTO EJEMPLO_DEFAULT(nif,nombre) VALUES ('1111A','Isabel');

--VISUALIZAR DATOS
SELECT * FROM EJEMPLO_DEFAULT;