SELECT *
FROM EMPLE
INNER JOIN DEPART ON EMPLE.DEPT_NO = DEPART.DEPT_NO
WHERE DNOMBRE = 'CONTABILIDAD';

UPDATE EMPLE
SET SALARIO = (SELECT SALARIO * 2
               FROM EMPLE
               WHERE APELLIDO = 'SANCHEZ')
WHERE DEPT_NO = (SELECT DEPT_NO
                 FROM DEPART
                 WHERE DNOMBRE = 'CONTABILIDAD');