--A)
DROP TABLE NOMBRES cascade constraints; 
CREATE TABLE NOMBRES
(
  NOMBRE VARCHAR2(15) primary key,
  EDAD NUMBER(2)
) ;

INSERT INTO NOMBRES VALUES('PEDRO', 17);
INSERT INTO NOMBRES VALUES('JUAN', 17);
INSERT INTO NOMBRES VALUES('MARÍA', 16);
INSERT INTO NOMBRES VALUES('CLARA', 14);
INSERT INTO NOMBRES VALUES('JESÚS', NULL);
commit;

INSERT INTO NOMBRES (NOMBRE)
    SELECT APELLIDO
    FROM EMPLE
    WHERE DEPT_NO = 20;
    
SELECT *
FROM NOMBRES;

--B)
CREATE TABLE DIRECTORES (
    EMP_NO    NUMBER(4) PRIMARY KEY,
    APELLIDO  VARCHAR2(10) UNIQUE,
    DIR       NUMBER(4) REFERENCES EMPLE ON DELETE SET NULL,
    FECHA_ALT DATE,
    SALARIO   NUMBER(7),
    COMISION  NUMBER(7),
    DEPT_NO   NUMBER(2) REFERENCES DEPART ON DELETE SET NULL
);

INSERT INTO DIRECTORES
    SELECT EMP_NO, APELLIDO, DIR, FECHA_ALT, SALARIO, COMISION, DEPT_NO
    FROM EMPLE
    WHERE OFICIO = 'DIRECTOR';

SELECT *
FROM DIRECTORES;