--A)
SELECT PROVINCIA, ESPECIE, COUNT(ESPECIE) CANTIDAD
FROM EJEMPLAR_ARBOL
GROUP BY PROVINCIA, ESPECIE
ORDER BY PROVINCIA ASC, ESPECIE ASC;

--B)
SELECT PROVINCIA, ESPECIE, MAX(AÑO_PLANT)
FROM EJEMPLAR_ARBOL
GROUP BY PROVINCIA, ESPECIE
ORDER BY PROVINCIA ASC, ESPECIE ASC;