--A)
SELECT * FROM EMPLE ORDER BY APELLIDO ASC;
--B)
SELECT * FROM EMPLE ORDER BY APELLIDO DESC;
--C)
SELECT APELLIDO FROM EMPLE ORDER BY SALARIO DESC;
--D)
SELECT EMP_NO, APELLIDO, OFICIO, SALARIO FROM EMPLE
ORDER BY OFICIO ASC, SALARIO DESC;