SELECT APELLIDO FROM EMPLE
WHERE OFICIO = (SELECT OFICIO FROM EMPLE
                WHERE EMP_NO = 7788);

SELECT * FROM EMPLE
WHERE SALARIO IN(SELECT SALARIO FROM EMPLE
                 WHERE DEPT_NO = 30);

SELECT * FROM EMPLE
WHERE SALARIO > (SELECT AVG(SALARIO) FROM EMPLE);