--A)
SELECT EMP_NO, APELLIDO, OFICIO, DNOMBRE, LOC FROM EMPLE E, DEPART D
WHERE E.DEPT_NO = D.DEPT_NO;

--B)
SELECT EMP_NO, APELLIDO, OFICIO, DNOMBRE, LOC FROM EMPLE E, DEPART D
WHERE E.DEPT_NO = D.DEPT_NO 
    AND OFICIO = 'ANALISTA';