--A)
SELECT APELLIDO FROM EMPLE
WHERE OFICIO = 'VENDEDOR' OR OFICIO = 'ANALISTA' OR OFICIO = 'DESARROLLADOR';

--B)
SELECT APELLIDO FROM EMPLE
WHERE OFICIO IN('VENDEDOR','ANALISTA','DESARROLLADOR');

--C)
SELECT DISTINCT OFICIO FROM EMPLE
WHERE OFICIO NOT IN('VENDEDOR','ANALISTA','DESARROLLADOR');

--D)
SELECT * FROM EMPLE
WHERE SALARIO BETWEEN 2000 AND 3000;

--E)
SELECT NOMBRE FROM ALUM22
WHERE NOMBRE BETWEEN 'ANA' AND 'CONCHA';