--A)
SELECT ROUND((NOTA1 + NOTA2 + NOTA3) / 3, 1) FROM NOTAS_ALUMNOS;
--B)
SELECT NOMBRE_ALUMNO, ROUND((NOTA1 + NOTA2 + NOTA3) / 3, 1) "NOTA REDONDEADA",
    (NOTA1 + NOTA2 + NOTA3) / 3 "NOTA SIN REDONDEO" FROM NOTAS_ALUMNOS
WHERE ROUND((NOTA1 + NOTA2 + NOTA3) / 3, 0) > 7;