SELECT * FROM EMPLE
WHERE OFICIO = (SELECT OFICIO FROM EMPLE
                WHERE EMP_NO = 7566);
                
SELECT APELLIDO, OFICIO, SALARIO FROM EMPLE
WHERE (DEPT_NO, SALARIO) = (SELECT DEPT_NO, SALARIO FROM EMPLE
                            WHERE APELLIDO = 'FERNANDEZ');