DROP TABLE PISO;
DROP TABLE PROPIETARIO;
DROP TABLE MUEBLE;
DROP TABLE PRECIO_ART;

CREATE TABLE PROPIETARIO
(
    dni VARCHAR2(9) PRIMARY KEY
);

CREATE TABLE PISO
(
    refer VARCHAR2(5) PRIMARY KEY,
    dni_propietario VARCHAR2(9),
    fecha_compra DATE NOT NULL,
        CONSTRAINT FK_DNI_INEXISTENTE FOREIGN KEY(dni_propietario)
            REFERENCES PROPIETARIO(dni)
);

CREATE TABLE MUEBLE
(
    cod VARCHAR2(3),
    alto NUMBER(4,2),
    ancho NUMBER(4,2),
    fondo NUMBER(4,2),
    precio NUMBER(5,2),
    stock NUMBER(4)
);

CREATE TABLE PRECIO_ART
(
    articulo VARCHAR2(10),
    valor NUMBER(5,-2),
    fecha DATE
);

--AÑADIR PK A MUEBLE
ALTER TABLE MUEBLE MODIFY cod PRIMARY KEY;
/* 
    Otra opción es: 
        ALTER TABLE MUEBLE ADD PRIMARY KEY(cod);
*/

--MODIFICAR CAMPO STOCK
ALTER TABLE MUEBLE MODIFY stock NUMBER(5);

--AÑADIR RESTRICCION
ALTER TABLE MUEBLE ADD CONSTRAINT C_FONDO_30_60 CHECK(fondo BETWEEN 30 AND 60);

--HACER QUE EL CAMPO VALOR SEA OBLIGATOIO
ALTER TABLE PRECIO_ART MODIFY valor NOT NULL;
/* 
    Otra opción es:
        ALTER TABLE PRECIO_ART ADD 
            CONSTRAINT C_VALOR_OBLIGATORIO CHECK(valor IS NOT NULL);
*/

--MODIFICAR CAMPO ARTICULO
ALTER TABLE PRECIO_ART MODIFY articulo VARCHAR(20);

--AÑADIR CAMPO cod_mueble
ALTER TABLE PISO ADD cod_mueble VARCHAR2(3);

--DESACTIVAR FK
ALTER TABLE PISO DISABLE CONSTRAINT FK_DNI_INEXISTENTE;

--AÑADIR CAMPO COLOR
ALTER TABLE MUEBLE ADD color VARCHAR2(10);

--AÑADIR RESTRICCION
ALTER TABLE PISO ADD CONSTRAINT FK_PISO_MUEBLE
    FOREIGN KEY(cod_mueble) REFERENCES MUEBLE(cod);
/* 
    Otra opción es: 
        ALTER TABLE PISO MODIFY cod_mueble CONSTRAINT FK_PISO_MUEBLE
            REFERENCES MUEBLE(cod);
*/
    
--BORRA CAMPO FECHA
ALTER TABLE PRECIO_ART DROP COLUMN fecha;