--CREAR TABLA
CREATE TABLE PRUEBA(
    prueba VARCHAR2(10) PRIMARY KEY
);

--INSERCIONES EN TELESCOPIO Y MONTURA
INSERT INTO STARSEE.TELESCOPIO(modelo) VALUES ('prueba');
INSERT INTO STARSEE.MONTURA(referencia) VALUES ('prueba');

--INSERCION EN PACK
INSERT INTO STARSEE.PACK(modelo,montura) VALUES ('prueba','prueba');

--INSERCIONES EN TABLAS
INSERT INTO STARSEE.TELESCOPIO 
    VALUES('REFRAC-700','refractor',11,'140x',700,70,26);
INSERT INTO STARSEE.MONTURA VALUES('al-06','altacimutal');
INSERT INTO STARSEE.MONTURA VALUES('al-07','altacimutal');
COMMIT;

