--BORRAR TABLA
DROP TABLE MONTE;

--CREAR TABLAS
CREATE TABLE MONTE
(
    nombre VARCHAR2(30),
    provincia VARCHAR2(30),
    altura NUMBER(4),
        CONSTRAINT PK_MONTE PRIMARY KEY(nombre),
        CONSTRAINT CHECK_ALTURA_MAS_2000 CHECK(altura>2000),
        CONSTRAINT NOT_NULL_ALTURA CHECK (altura IS NOT NULL)
);

ALTER TABLE MONTE DROP CONSTRAINT CHECK_ALTURA_MAS_2000;
ALTER TABLE MONTE ADD CONSTRAINT CHECK_ALTURA_MAS_1000 CHECK (altura>1000);
INSERT INTO MONTE VALUES ('PUIG MAJOR', 'ISLAS BALEARES', 1445);

ALTER TABLE MONTE DROP CONSTRAINT CHECK_ALTURA_MAS_1000;
ALTER TABLE MONTE ADD CONSTRAINT CHECK_ALTURA_MAS_1500 CHECK (altura>1500);
/* No es posible porque el registro introducido no cumple el CHECK, habría
que borrarlo o modificarlo con un UPDATE */