--CREAR USUARIO STARSEE EN XEPDB1
ALTER SESSION SET CONTAINER = XEPDB1;
CREATE USER STARSEE IDENTIFIED BY f7xV7m4GgN# QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO STARSEE;
GRANT CREATE TABLE TO STARSEE;

--CREAR ROLES
CREATE ROLE INGENIERIA;
GRANT INSERT, UPDATE, DELETE ON STARSEE.TELESCOPIO TO INGENIERIA;
GRANT INSERT, UPDATE, DELETE ON STARSEE.MONTURA TO INGENIERIA;


CREATE ROLE MARKETING;
GRANT INSERT, UPDATE, DELETE ON STARSEE.PACK TO MARKETING;

--CREAR USUARIOS
/* Creación base de los usuarios */
CREATE USER nbaeza IDENTIFIED BY nbaeza QUOTA UNLIMITED ON USERS;
CREATE USER rherraiz IDENTIFIED BY rherraiz QUOTA UNLIMITED ON USERS;
CREATE USER jpulido IDENTIFIED BY jpulido QUOTA UNLIMITED ON USERS;

/* Permiso de creación de sesion */
GRANT CREATE SESSION TO nbaeza, rherraiz, jpulido;

/* Asignación de roles */
GRANT INGENIERIA TO nbaeza, rherraiz;
GRANT MARKETING TO jpulido;

/* Definición de rol por defecto */
ALTER USER nbaeza DEFAULT ROLE INGENIERIA;
ALTER USER rherraiz DEFAULT ROLE INGENIERIA;
ALTER USER jpulido DEFAULT ROLE MARKETING;

--CREACIÓN Y ASIGNACIÓN DE PERFIL
/* Creación del perfil */
CREATE PROFILE EMPLEADO_STARSEE LIMIT
SESSIONS_PER_USER 1
FAILED_LOGIN_ATTEMPTS 5
PASSWORD_LIFE_TIME 30;

/* Asignación a los usuarios */
ALTER USER nbaeza PROFILE EMPLEADO_STARSEE;
ALTER USER rherraiz PROFILE EMPLEADO_STARSEE;
ALTER USER jpulido PROFILE EMPLEADO_STARSEE;

--ELIMINAR USUARIO
DROP USER rherraiz;