--1.1
CREATE OR REPLACE TYPE TIPO_MIEMBROESCOLAR AS OBJECT(
    NIF             CHAR(9),
    NOMBRECOMPLETO  VARCHAR2(50)
) NOT FINAL;
/

CREATE OR REPLACE TYPE TIPO_DOCENTE
UNDER TIPO_MIEMBROESCOLAR(
    ESPECIALIDAD    VARCHAR2(20),
    ANTIGUEDAD      NUMBER(2),
    MEMBER FUNCTION TRIENIOS RETURN NUMBER
);
/

CREATE OR REPLACE TYPE BODY TIPO_DOCENTE
    AS MEMBER FUNCTION TRIENIOS RETURN NUMBER
        AS
        BEGIN
            RETURN ROUND((ANTIGUEDAD / 3), 1);
        END;
END;
/

CREATE OR REPLACE TYPE TIPO_CURSO AS OBJECT(
    NOMBRE      VARCHAR2(20),
    DOCENTE     TIPO_DOCENTE,
    MAX_ALUM    NUMBER(3),
    FECHA_INI   DATE,
    FECHA_FIN   DATE,
    NUM_HORAS   NUMBER(2)
);
/

CREATE OR REPLACE TYPE TIPO_ESTUDIANTE
UNDER TIPO_MIEMBROESCOLAR(
    NIA             NUMBER(5),
    CURSOESTUDIANTE TIPO_CURSO
);
/

SELECT *
FROM USER_TYPES;

--1.2
CREATE TABLE PROFESORADO OF TIPO_DOCENTE;

INSERT INTO PROFESORADO
    VALUES('51083098F', 'María Luisa Fabre', 'Tecnología', 4);
INSERT INTO PROFESORADO
    VALUES('51083099F', 'Javier Jiménez', 'Inglés', 9);

--1.3
DROP TABLE PROFESORADO;

CREATE TABLE PROFESORADO(
    CODIGO  NUMBER  PRIMARY KEY,
    DOCENTE TIPO_DOCENTE,
    SALARIO NUMBER(7,2)
);

INSERT INTO PROFESORADO
    VALUES(82, TIPO_DOCENTE('51083098F', 'María Luisa Fabre', 'Tecnología', 4), 
        2500);
INSERT INTO PROFESORADO
    VALUES(83, TIPO_DOCENTE('51083099F', 'Javier Jiménez', 'Inglés', 9), 2100);
    
SELECT CODIGO, P.DOCENTE.NOMBRECOMPLETO "NOMBRE", SALARIO, 
    P.DOCENTE.ANTIGUEDAD "ANTIGÜEDAD", P.DOCENTE.TRIENIOS()"TRIENIOS"
FROM PROFESORADO P;

--1.4
CREATE OR REPLACE TYPE TIPO_LISTACURSOS
AS VARRAY(10) OF TIPO_CURSO;
/

CREATE TABLE CURSOS_PROMOCION_LISTA(
    FECHA   DATE    PRIMARY KEY,
    CURSOS  TIPO_LISTACURSOS
);

--1.5
CREATE OR REPLACE TYPE TIPO_TABLACURSOS
AS TABLE OF TIPO_CURSO;
/

CREATE TABLE CURSOS_PROMOCION_TABLA(
    FECHA   DATE    PRIMARY KEY,
    CURSOS  TIPO_TABLACURSOS
) NESTED TABLE CURSOS STORE AS T_CURSOS;