--A)
SELECT EMP_NO, APELLIDO, (SALARIO + COMISION) "SUELDO COMPLETO" FROM EMPLE;
--B)
SELECT EMP_NO, APELLIDO, (SALARIO + NVL(COMISION,0)) "SUELDO COMPLETO" 
FROM EMPLE;
--C)
SELECT ROUND((NVL(NOTA1, 0) + NVL(NOTA2, 0) + NVL(NOTA3, 0)) / 3 ,1) "NOTA MEDIA"
FROM NOTAS_ALUMNOS;