Drop table LIBRERIA cascade constraints;

create table LIBRERIA
 (TEMA CHAR(15) PRIMARY KEY,
  ESTANTE CHAR(1),
  EJEMPLARES NUMBER(2)
 );

INSERT INTO LIBRERIA VALUES ('INFORMATICA', 'A',15);
INSERT INTO LIBRERIA VALUES ('ECONOMIA',    'A',10);
INSERT INTO LIBRERIA VALUES ('DEPORTES',    'B',8);
INSERT INTO LIBRERIA VALUES ('FILOSOFIA',   'C',7);
INSERT INTO LIBRERIA VALUES ('DIBUJO',      'C',10);
INSERT INTO LIBRERIA VALUES ('MEDICINA',    'C',16);
INSERT INTO LIBRERIA VALUES ('BIOLOGIA',    'A',11);
INSERT INTO LIBRERIA VALUES ('GEOLOGIA',    'D',7);
INSERT INTO LIBRERIA VALUES ('SOCIEDAD',    'D',9);
INSERT INTO LIBRERIA VALUES ('LABORES',     'B',20);
INSERT INTO LIBRERIA VALUES ('JARDINERIA',  'E',6);

commit;

--A)
SELECT * FROM LIBRERIA;
DESCRIBE LIBRERIA;

--B)
SELECT * FROM LIBRERIA
WHERE TEMA = 'LABORES';

SELECT * FROM LIBRERIA
WHERE TEMA LIKE 'LABORES%';

--C)
SELECT * FROM ALUM22
WHERE NOMBRE = 'CONCHA';

SELECT * FROM ALUM22
WHERE NOMBRE LIKE 'CONCHA%';