--A)
SELECT * FROM EMPLE
ORDER BY OFICIO;

SELECT COUNT(DISTINCT OFICIO) FROM EMPLE;

--B)
SELECT COUNT(*) FROM EMPLE
WHERE APELLIDO LIKE 'A%';

--C)
SELECT COUNT(DISTINCT APELLIDO) FROM EMPLE
WHERE APELLIDO LIKE 'A%';

--D)
SELECT COUNT(*) FROM EMPLE;

SELECT COUNT(APELLIDO) FROM EMPLE;

SELECT COUNT(COMISION) FROM EMPLE;