CREATE OR REPLACE FUNCTION MEDIA_DEP (P_DEPARTAMENTO EMPLE.DEPT_NO%TYPE)
RETURN NUMBER
AS
    V_MEDIA_SALARIO EMPLE.SALARIO%TYPE;
BEGIN
    SELECT ROUND(AVG(SALARIO),0)
    INTO V_MEDIA_SALARIO
    FROM EMPLE
    WHERE DEPT_NO = P_DEPARTAMENTO;
    
    RETURN V_MEDIA_SALARIO;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN NULL;
END;
/

SELECT MEDIA_DEP(10)
FROM DUAL;