CREATE OR REPLACE TRIGGER CHECK_SALARIO
BEFORE INSERT ON EMPLE
FOR EACH ROW
BEGIN
    IF :NEW.SALARIO < MEDIA_DEP(:NEW.DEPT_NO) THEN
        DBMS_OUTPUT.PUT_LINE('AVISO: Este empleado cobra por debajo'
            || ' de la media de su departamento.');
    END IF;
END;
/

SELECT DEPT_NO, AVG(SALARIO)
FROM EMPLE
GROUP BY DEPT_NO;

INSERT INTO EMPLE (EMP_NO, APELLIDO, SALARIO, DEPT_NO)
    VALUES (4444,'JUAN', 1000, 10);
