--IF-ELSE
DECLARE
    V_CANTIDAD_EMPLEADOS NUMBER(2);
    V_NUMERO_EMPLEADO EMPLE.EMP_NO%TYPE;
    V_SUBIDA_SALARIO EMPLE.SALARIO%TYPE;
BEGIN
    V_NUMERO_EMPLEADO := &EMP_NUMERO;
    
    SELECT COUNT(EMP_NO) INTO V_CANTIDAD_EMPLEADOS
    FROM EMPLE
    WHERE DIR = V_NUMERO_EMPLEADO;
    
    IF V_CANTIDAD_EMPLEADOS = 0 THEN
        V_SUBIDA_SALARIO := 0;
    ELSIF V_CANTIDAD_EMPLEADOS = 1 THEN
        V_SUBIDA_SALARIO := 80;
    ELSIF V_CANTIDAD_EMPLEADOS = 2 THEN
        V_SUBIDA_SALARIO := 100;
    ELSE
        V_SUBIDA_SALARIO := 150;
    END IF;
    
    UPDATE EMPLE
        SET SALARIO = SALARIO + V_SUBIDA_SALARIO
        WHERE EMP_NO = V_NUMERO_EMPLEADO;
        
    DBMS_OUTPUT.PUT_LINE('Al empleado ' || V_NUMERO_EMPLEADO || 
        ' se le ha realizado una subida salarial de ' || V_SUBIDA_SALARIO || 
        ' euros, al tener ' || V_CANTIDAD_EMPLEADOS || 
        ' empleados a su cargo.');
END;
/

--CASE CON EXPRESION
DECLARE
    V_CANTIDAD_EMPLEADOS NUMBER(2);
    V_NUMERO_EMPLEADO EMPLE.EMP_NO%TYPE;
    V_SUBIDA_SALARIO EMPLE.SALARIO%TYPE;
BEGIN
    V_NUMERO_EMPLEADO := &EMP_NUMERO;
    
    SELECT COUNT(EMP_NO) INTO V_CANTIDAD_EMPLEADOS
    FROM EMPLE
    WHERE DIR = V_NUMERO_EMPLEADO;
    
    CASE V_CANTIDAD_EMPLEADOS
    WHEN 0 THEN
        V_SUBIDA_SALARIO := 0;
    WHEN 1 THEN
        V_SUBIDA_SALARIO := 80;
    WHEN 2 THEN
        V_SUBIDA_SALARIO := 100;
    ELSE
        V_SUBIDA_SALARIO := 150;
    END CASE;
    
    UPDATE EMPLE
        SET SALARIO = SALARIO + V_SUBIDA_SALARIO
        WHERE EMP_NO = V_NUMERO_EMPLEADO;
    
    DBMS_OUTPUT.PUT_LINE('Al empleado ' || V_NUMERO_EMPLEADO || 
        ' se le ha realizado una subida salarial de ' || V_SUBIDA_SALARIO || 
        ' euros, al tener ' || V_CANTIDAD_EMPLEADOS || 
        ' empleados a su cargo.');
END;
/

--CASE SIN EXPRESIÓN
DECLARE
    V_CANTIDAD_EMPLEADOS NUMBER(2);
    V_NUMERO_EMPLEADO EMPLE.EMP_NO%TYPE;
    V_SUBIDA_SALARIO EMPLE.SALARIO%TYPE;
BEGIN
    V_NUMERO_EMPLEADO := &EMP_NUMERO;
    
    SELECT COUNT(EMP_NO) INTO V_CANTIDAD_EMPLEADOS
    FROM EMPLE
    WHERE DIR = V_NUMERO_EMPLEADO;
    
    CASE 
    WHEN V_CANTIDAD_EMPLEADOS = 0 THEN
        V_SUBIDA_SALARIO := 0;
    WHEN V_CANTIDAD_EMPLEADOS = 1 THEN
        V_SUBIDA_SALARIO := 80;
    WHEN V_CANTIDAD_EMPLEADOS = 2 THEN
        V_SUBIDA_SALARIO := 100;
    ELSE
        V_SUBIDA_SALARIO := 150;
    END CASE;
    
    UPDATE EMPLE
        SET SALARIO = SALARIO + V_SUBIDA_SALARIO
        WHERE EMP_NO = V_NUMERO_EMPLEADO;
    
    DBMS_OUTPUT.PUT_LINE('Al empleado ' || V_NUMERO_EMPLEADO || 
        ' se le ha realizado una subida salarial de ' || V_SUBIDA_SALARIO || 
        ' euros, al tener ' || V_CANTIDAD_EMPLEADOS || 
        ' empleados a su cargo.');
END;
/