DROP TABLE ALUM cascade constraints;
DROP TABLE NUEVOS cascade constraints;
DROP TABLE ANTIGUOS cascade constraints;

Create TABLE ALUM
(
  NOMBRE VARCHAR2(20) primary key,
 EDAD NUMBER(2),
 LOCALIDAD VARCHAR2(15)
) ;

Create TABLE  NUEVOS
(
  NOMBRE  VARCHAR2(20) primary key,
 EDAD NUMBER(2),
 LOCALIDAD VARCHAR2(15)
) ;

Create TABLE ANTIGUOS
(
  NOMBRE  VARCHAR2(20) primary key,
 EDAD NUMBER(2),
 LOCALIDAD VARCHAR2(15)
) ;

INSERT INTO ALUM VALUES('JUAN',18,'COSLADA');
INSERT INTO ALUM VALUES('PEDRO',19,'COSLADA');
INSERT INTO ALUM VALUES('ANA',17,'ALCALÁ');
INSERT INTO ALUM VALUES('LUISA',18,'TORREJÓN');
INSERT INTO ALUM VALUES('MARÍA',20,'MADRID');
INSERT INTO ALUM VALUES('ERNESTO',21,'MADRID');
INSERT INTO ALUM VALUES('RAQUEL',19,'TOLEDO');

INSERT INTO NUEVOS VALUES('JUAN',18,'COSLADA');
INSERT INTO NUEVOS VALUES('MAITE',15,'ALCALÁ');
INSERT INTO NUEVOS VALUES('SOFÍA',14,'ALCALÁ');
INSERT INTO NUEVOS VALUES('ANA',17,'ALCALÁ');
INSERT INTO NUEVOS VALUES('ERNESTO',21,'MADRID');

INSERT INTO ANTIGUOS VALUES('MARÍA',23,'MADRID');
INSERT INTO ANTIGUOS VALUES('ERNESTO',21,'MADRID');
INSERT INTO ANTIGUOS VALUES('ANDRÉS',26,'LAS ROZAS');
INSERT INTO ANTIGUOS VALUES('IRENE',24,'LAS ROZAS');

COMMIT;

/* a. Visualiza los nombre de los alumnos de la tabla ALUM que aparezcan 
      en estas dos tablas: ANTIGUOS y NUEVOS. */
SELECT A.NOMBRE
FROM ALUM A
INNER JOIN ANTIGUOS AN ON A.NOMBRE = AN.NOMBRE
INNER JOIN NUEVOS N ON A.NOMBRE = N.NOMBRE;

/* b. Escribe las distintas formas en que se puede poner la consulta anterior
      llegando al mismo resultado. */
SELECT A.NOMBRE
FROM ALUM A, ANTIGUOS AN, NUEVOS N
WHERE A.NOMBRE = AN.NOMBRE AND A.NOMBRE = N.NOMBRE;

SELECT NOMBRE
FROM ALUM
WHERE NOMBRE IN (SELECT NOMBRE
                 FROM ANTIGUOS
                 WHERE NOMBRE IN (SELECT NOMBRE
                                  FROM NUEVOS));

SELECT NOMBRE FROM ALUM
INTERSECT
SELECT NOMBRE FROM ANTIGUOS
INTERSECT
SELECT NOMBRE FROM NUEVOS;

/* c. Visualiza aquellos nombres de la tabla ALUM que no estén en la tabla
      ANTIGUOS ni en la tabla NUEVOS. */
SELECT NOMBRE
FROM ALUM
WHERE NOMBRE NOT IN (SELECT NOMBRE 
                     FROM ANTIGUOS)
    AND NOMBRE NOT IN (SELECT NOMBRE
                       FROM NUEVOS);
      
SELECT NOMBRE FROM ALUM
MINUS
SELECT NOMBRE FROM ANTIGUOS
MINUS
SELECT NOMBRE FROM NUEVOS;